### PR TITLE
Google Drive icon

### PR DESCRIPTION
**Pull request by rubenmoya**
Added icon for Google Drive.

Extension name: apdfllckaahabafndbhieahigkjlhalf

drive

### CODE REVIEW

**Comment by loctauxphilippe** [comment]
looks good for me

**Comment by UriHerrera** [comment]
Is it aligned?

**Comment by c42759** [comment]
@UriHerrera in my vision, it's impossible align this logo.
The logo aren't using 45º, some like 66º

Just an idea!
google-drive-48

google-drive-192

**Comment by loctauxphilippe** [comment]
I'd make the white triangle bigger

**Comment by c42759** [comment]
google-drive-2-192

**Comment by loctauxphilippe** [comment]
yea I prefer this one :)

**Comment by UriHerrera** [comment]
I liked that last one too.

**Comment by c42759** [comment]
you want me to do a PR?

**Comment by loctauxphilippe** [comment]
What did you changed since the last icon? Just to know

**Comment by c42759** [comment]
3 layers create a red effect on left side of yellow

compare the last 2

**Comment by loctauxphilippe** [comment]
oh ok I see :)

**Pull request merged**
