### PR TITLE
Added Viber icon

### PR DESCRIPTION
**Pull request by rubenmoya**
Added Viber and TeamSpeak icons.

Viber icon name: `Icon=/usr/share/pixmaps/viber.png`.

viber

(btw, it added a TS3 Icon by error)

### CODE REVIEW

**Comment by me4oslav** [comment]
The gradient should be just vertical, not diagonal vertical. Is that inset shadow on the purple square needed? Actually do we need square inside a square design?
I would suggest making the main baseplate with purple gradient and just putting the symbol on it. But add a light purple to white gradient (bottom to top) on the symbol.

**Comment by rubenmoya** [comment]
It's better now?

viber

**Comment by me4oslav** [comment]
Definitely. Although the light purple should be light.

**Comment by rubenmoya** [comment]
Something like this?

Anyway, I have to make a new pull request (i think) because I deleted the fork... so I can't change the files on this pull request.

viber

**Comment by me4oslav** [comment]
Lighter light purple.

**Comment by rubenmoya** [comment]
I don't know if you mean the base gradient or the icon gradient.

**Comment by me4oslav** [comment]
The symbol one.

**Pull request closed without merging**
