### PR TITLE
Google Maps and Calendar applications

### PR DESCRIPTION
**Pull request by aenima1985**
google-maps
office-calendar

### CODE REVIEW

**Comment by UriHerrera** [comment]
1) Shadows go 1 px below whatever the object is. Not in any other direction.
20 Are they aligned to the grid in Inkscape?.

**Comment by aenima1985** [comment]
Fixed shadows, object should be well aligned now.
google-maps
office-calendar

**Comment by me4oslav** [comment]
@UriHerrera, should we merge them?

**Comment by UriHerrera** [comment]
Yeah.

**Comment by loctauxphilippe** [comment]
@aenima1985 nice icons!

**Comment by aenima1985** [comment]
@loctauxphilippe thank you!

**Pull request merged**
