### PR TITLE
rss.svg

### PR DESCRIPTION
**Pull request by c42759**
rss-48 rss-192

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
Can you smylink this to feedreader?

**Comment by c42759** [comment]
@bil-elmoussaoui I don't know how to do an symlink

**Comment by bil-elmoussaoui** [comment]
Go the folder of icons using your terminal and then run this 
``` ln -s rss.svg feedreader.svg ```

**Comment by c42759** [comment]
how can I do a PR of a symlink?

**Comment by bil-elmoussaoui** [comment]
You just create the symlink and then you do a normal PR like you do for a normal icon

**Comment by c42759** [comment]
I don't use the Terminal for a PR

**Comment by bil-elmoussaoui** [comment]
i'm going to do this @c42759

**Pull request merged**
