### PR TITLE
Google Keep

### PR DESCRIPTION
**Pull request by c42759**
icon-48 icon-192

### CODE REVIEW

**Comment by loctauxphilippe** [comment]
What's chrome keep? I've never heard of that

**Comment by PhnxRbrn** [comment]
I assume he is referring to Google keep the note taking app

**Comment by loctauxphilippe** [comment]
@PhnxRbrn Yea I think also, I'm not sure so I ask :)

**Comment by c42759** [comment]
@PhnxRbrn & @loctauxphilippe it's Google Keep ;)

**Comment by loctauxphilippe** [comment]
@c42759 oh ok! :-)

**Pull request merged**
