### PR TITLE
Added eclipse icon

### PR DESCRIPTION
**Pull request by williamnerdy**
Prevew

### CODE REVIEW

**Comment by williamnerdy** [comment]
prevew

**Comment by UriHerrera** [comment]
@williamnerdy The "eclipse" isn't centered. But looks good.

**Comment by me4oslav** [comment]
Maybe a bit lighter, also.

**Comment by williamnerdy** [comment]
Prevew

**Comment by williamnerdy** [comment]
Prevew

**Comment by me4oslav** [comment]
Better. @UriHerrera, thoughts?

**Comment by UriHerrera** [comment]
Good, but it's still no centered.

**Comment by me4oslav** [comment]
Well, @williamnerdy fix the centring and we can merge it.

**Comment by williamnerdy** [comment]
Prevew

**Comment by UriHerrera** [comment]
Move the dark circle, its shadow and the rightmost part of the lines 1px to the left.

**Comment by me4oslav** [comment]
Can we get a preview of the latest version?

**Comment by williamnerdy** [comment]
prevew

**Comment by me4oslav** [comment]
Looks ok to me. @UriHerrera, should we merge it?

**Comment by UriHerrera** [comment]
Yeah.

**Comment by me4oslav** [comment]
Merging.

**Comment by me4oslav** [comment]
@williamnerdy I had to align the icon to a grid. The lines and the dark circle were improperly aligned and as a result were looking blurry. Please make sure you align stuff to grid, next time. :)

**Pull request merged**
