### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by loctauxphilippe**
added ubuntu package

### CODE REVIEW

**Comment by Foggalong** [comment]
Single line that shit and uppercase PPA

**Comment by loctauxphilippe** [comment]
@Foggalong no problem! :)

**Comment by loctauxphilippe** [comment]
like this?

**Comment by Foggalong** [comment]
Noo

```markdown
Arch users can install this community maintained [AUR package](https://aur.archlinux.org/packages/ozon-icon-theme-git/). Ubuntu users can install using our [PPA](https://launchpad.net/~ozonos/+archive/ubuntu/ppa). Otherwise, [download the source](https://github.com/ozonos/ozon-icon-theme/archive/master.zip), extract it, and copy the "Ozon" folder to one of the following icon theme locations:
```

**Comment by loctauxphilippe** [comment]
@Foggalong hopefully the third one is the good one :)

**Pull request merged**
