### PR TITLE
Icons for Qt4 Designer & Linguist+OpenArena revised icons

### PR DESCRIPTION
**Pull request by mydegeneration**
Qt4 Linguist
screenshot from 2015-01-11 20 50 24

Qt4 Designer
screenshot from 2015-01-11 20 50 38

OpenArena
screenshot from 2015-01-11 20 52 38

OpenArena Server
screenshot from 2015-01-11 20 52 58

### CODE REVIEW

**Comment by me4oslav** [comment]
Isn't there already an openarena icon?
openarena-server? How does sumpky a red coloured background indicate the server bit?
QT apps: The laws of physics get broken with the 3D logos and the standard shadows. Oh and the blue bubble doesn't play at all at that background, it sticks out way too much. I like the gird on the designer icon, though.

**Comment by mydegeneration** [comment]
OpenArena icon: I noticed the were some flaws with the previous OpenArena icon I made before so I fixed them.
Server icon: the only reason I just changed the background is because I was just following the guideline from the original
openarena
openarena-server
What do you suggest for the server icon?

Qt icons:
So remove the shadow for the designer logo?
What color should I use for the bubble of the linguist icon?

**Comment by me4oslav** [comment]
Openarena - I see now. Perhaps adding some transparent continents (take them from the web browser icon) below the logo would make it even better.
QT apps - I think I would prefer for the 3D-esque shadow to go. @UriHerrera, which shadow you want gone?
QT linguist - Just make a different bubble (https://www.iconfinder.com/search/?q=chat+bubble), vut the QT letters inside the bubbles, make the bubble super light green to white gradient (bottom to top) coloured and add the 1px ptch black 15% opaque below shadow.

**Comment by UriHerrera** [comment]
The one on the left of the Qt logo, that shouldn't be there.

**Comment by me4oslav** [comment]
Yeah, that's what I meant with the 3D-esque shadow. @mydegeneration, it is settled then.

**Comment by mydegeneration** [comment]
That shadow on the left is part of the Qt logo which is why I kept it http://i1-linux.softpedia-static.com/screenshots/Qt_1.jpg @me4oslav @UriHerrera

**Comment by me4oslav** [comment]
But with our icons it breaks the physic's laws.

**Comment by mydegeneration** [comment]
screenshot from 2015-01-11 20 52 38
screenshot from 2015-01-14 19 54 48
screenshot from 2015-01-14 19 02 54
screenshot from 2015-01-14 19 29 45

**Comment by mydegeneration** [comment]
I'm afraid the continents at 30% are too transparent so here it is at 60%
screenshot from 2015-01-14 20 00 56

Let me know what you guys think.

**Comment by me4oslav** [comment]
Openarena - fine.
Openarena server - how about nuking the shadow of the continents and making them 45% opaque?
QTdesigner - fine.
QTlinguist - perhaps make the top stop of the top bubble gradient a bit less light?

**Comment by me4oslav** [comment]
Oh and you should consider adding gradients to the QT and openarena logos to avoid the plain white symbols.

**Comment by UriHerrera** [comment]
Why not using the symbolic network icon for the backgroun in the openarena server icon. The color of the bubble looks really bright and fluorescent.

**Comment by me4oslav** [comment]
Or that (the idea for the symbolic network icon).
It also seems both me and uri think that the bubble colouring needs adjustments.

**Comment by mydegeneration** [comment]
screenshot from 2015-01-15 11 53 04
screenshot from 2015-01-15 12 02 39
screenshot from 2015-01-15 12 08 32

**Comment by UriHerrera** [comment]
That uhmm no.. there's a network-**server**-symbolic and network-wrokgroup-symbolic use those.

Linguistic is fine.

**Comment by me4oslav** [comment]
I also agree that linguist is fine.
Try openarena-server with the network-server-symbolic (status) and network-workgroup-symbolic for it apparently doesn't play well with network-wired. If those two such too I guess we will go with the world map (only with maybe 40 or 45 opaque continents).

**Comment by mydegeneration** [comment]
They're all at 45% transparency.
screenshot from 2015-01-15 11 53 04
screenshot from 2015-01-15 12 50 21
screenshot from 2015-01-15 12 50 55

**Comment by UriHerrera** [comment]
Last one, it's evidently the one that says *server*. The other two look like a web browser.

**Comment by mydegeneration** [comment]
Cool. Let me do the pull again.

**Comment by me4oslav** [comment]
Why can't we merge we automagically? ;(

**Comment by UriHerrera** [comment]
Because there's conflicts.

**Comment by me4oslav** [comment]
Damn. With which icon?

**Comment by UriHerrera** [comment]
According to Github, his branch is 6 commites ahead (these icons) and 177 commits *behind*.

**Comment by me4oslav** [comment]
Ah. @mydegeneration update, then.

**Comment by mydegeneration** [comment]
Wait, how do I update?

**Comment by UriHerrera** [comment]
Use git pull.

**Pull request closed without merging**
