### PR TITLE
Update minecraft.svg

### PR DESCRIPTION
**Pull request by c42759**
g3589

### CODE REVIEW

**Comment by loctauxphilippe** [comment]
looks good for me, and looks like it's aligned

**Comment by UriHerrera** [comment]
You can clearly see that the separation between the objects in the image, that shouldn't happen.

**Comment by c42759** [comment]
@UriHerrera I will check the problem and redo the icon ;)

**Comment by c42759** [comment]
128px
mine

48px
mine_48

**Comment by Foggalong** [comment]
@c42759 would it not be possible to merge all the adjacent black squares into one shape? that would at least remove the most striking of the gaps

**Comment by UriHerrera** [comment]
Or a dark background.

**Comment by c42759** [comment]
done!  :+1: 

mine_48

mine_192

**Pull request merged**
