### PR TITLE
added a RSS Icon for RSS Readers

### PR DESCRIPTION
**Pull request by jarheadcore**
rss

cheers

### CODE REVIEW

**Comment by me4oslav** [comment]
Add super light orange to white to the symbol. Also the background gradients should be lighter (top) to darker (bottom). Lastly, is everything aligned to grid?
@UriHerrera, thoughts?

**Comment by jarheadcore** [comment]
added some light orange to white gradient in the symbol and gradient is now from brighter (top) to darker (bottom).. I also checked the alignment of the symbol..
cheers

**Comment by jarheadcore** [comment]
rss

**Comment by jarheadcore** [comment]
maybe it needs to be a bit more on the left to look better (now the alignment is calculated without the shadow) but maybe it needs some slightly more positioning to the left...

**Comment by loctauxphilippe** [comment]
@jarheadcore I like this one but I'm not the boss here

**Comment by me4oslav** [comment]
@jarheadcore The first background was just just fine, but its gradient needs to be reversed.
The symbol gradient is now fine.
Aligned wise - open the svg in Inkscap, maximise the window, enable the grid (view - grid), press "5" and send a screenie of that window.

**Comment by UriHerrera** [comment]
The first gradient colors were fine. Shadows go 1 px below the main symbol, not in any other direction.

**Comment by jarheadcore** [comment]
rss
the fixed icon

alignment preview
alignment_rss

**Comment by UriHerrera** [comment]
It's not aligned, you can recreate the RSS symbol using the circle tool in Inkscape.

**Comment by me4oslav** [comment]
Yes, please align it to grid.

**Comment by c42759** [comment]
an remake and aligned based on PR icon

rss-48 rss-192

**Comment by loctauxphilippe** [comment]
@c42759 You do a lot of work these days haha! :smile:

**Comment by c42759** [comment]
@loctauxphilippe my old account was @NexuS-Pt , but I move it to an organization ;)

I do a lot work with that account :D

**Comment by loctauxphilippe** [comment]
@c42759 oh I see! That's good if you work a lot! :)

**Comment by UriHerrera** [comment]
Do a PR @c42759

**Comment by c42759** [comment]
@UriHerrera https://github.com/ozonos/ozon-icon-theme/pull/186

**Pull request closed without merging**
