### PR TITLE
Create MegaSync icon

### PR DESCRIPTION
**Pull request by williamnerdy**
Prevew

### CODE REVIEW

**Comment by UriHerrera** [comment]
I guess it's fine, but add a subtle gradient to the letter. There's quite a few plain white symbol icons.

**Comment by williamnerdy** [comment]
Better?
Prevew

**Comment by UriHerrera** [comment]
A red gradient would be better.

**Comment by me4oslav** [comment]
What the taco buy said.

**Comment by williamnerdy** [comment]
Better?
Prevew

**Comment by UriHerrera** [comment]
Yes better. Is it aligned? is the shadow aligned?.

**Comment by williamnerdy** [comment]
Yes!

**Comment by loctauxphilippe** [comment]
Yay! now I have an icon for mega! Thank @williamnerdy !

**Comment by williamnerdy** [comment]
:smile:

**Pull request merged**
