### PR TITLE
Create obs.svg

### PR DESCRIPTION
**Pull request by c42759**
obs

### CODE REVIEW

**Comment by me4oslav** [comment]
@UriHerrera, thoughts?

**Comment by UriHerrera** [comment]
Well it looks cool, what's it for?.

**Comment by c42759** [comment]
@UriHerrera it's a open source broadcaster, I use it to make game stream to twitch.tv

**Comment by UriHerrera** [comment]
Perhaps a more Twitch-esque icon? unless there's another app that does the same as this one.

**Comment by c42759** [comment]
@UriHerrera exist a good list for it ;)

**Comment by UriHerrera** [comment]
Ah well then I guess this is fine then.

**Pull request merged**
