### PR TITLE
Icon for Gufw Firewall

### PR DESCRIPTION
**Pull request by mydegeneration**
screenshot from 2015-01-22 21 43 09

### CODE REVIEW

**Comment by UriHerrera** [comment]
It literally is a fire and a wall.. but it's I don't know not ok. Try with something more security oriented.

**Comment by me4oslav** [comment]
Although I kinda like the icon from artistic point of view, I agree with Uri.

**Comment by mydegeneration** [comment]
screenshot from 2015-02-02 14 19 19

**Comment by me4oslav** [comment]
Better.
@UriHerrera, thoughts?

**Comment by UriHerrera** [comment]
Almost, not quite there yet. Something more "secure", it looks more like "police don't cross".

**Comment by mydegeneration** [comment]
Alright, I'll come up with something.

P.S. I am also working on something for Aisleriot
screenshot from 2015-02-02 16 07 46

**Comment by me4oslav** [comment]
I am horrendous at all sorts of gaming icons. Maybe because I don't play games, my mind fall into catatonic state when I have to do/review a game icon (even for simple cards game).

**Comment by UriHerrera** [comment]
It looks fine although the gradient should be bottom to top.

**Comment by mydegeneration** [comment]
screenshot from 2015-02-05 20 05 23
screenshot from 2015-02-05 20 06 19

**Comment by UriHerrera** [comment]
The perspective of the lock is wrong it looks like it's leaning forward, also the background has the gradient inverted.

Create a different issue/pull request for the aisleriot icon.

**Pull request closed without merging**
